"""
06_merge_realtime.py
--------------------
Merge the calculated vehicle-position delays (from 04c_calculate_delays.py)
with the cleaned + weather GTFS static DataFrame to produce the final
modelling dataset.

Source of delay data
--------------------
  data/raw/calculated_delays_all.csv
  Generated by 04c_calculate_delays.py — one row per unique
  (trip_id, stop_sequence) pair, deduplicated to the largest |delay|
  observed across all collected vehicle-position snapshots.

Join key
--------
  (trip_id, stop_sequence) — stop-level, avoids row explosion.
  GTFS rows with no delay observation keep NaN for delay columns
  and is_delayed = 0.

Columns added from delay data
------------------------------
  delay_minutes        actual_delay / 60  (+ = late, - = early)
  is_delayed           1 if delay_minutes > 5 else 0
  speed_mph            vehicle speed at observation time
  occupancy_label      passenger load label (EMPTY / FEW_SEATS / …)
  vehicle_id           vehicle that was observed
  current_status_name  INCOMING_AT / IN_TRANSIT_TO / STOPPED_AT
  delay_snapshot_ts    timestamp of the GPS observation used

Outputs
-------
  data/cleaned/vta_final.parquet
  data/cleaned/vta_final.csv       (timedelta cols as total seconds)
"""

from pathlib import Path

import pandas as pd

ROOT    = Path(__file__).resolve().parent
RAW     = ROOT / "data" / "raw"
CLEANED = ROOT / "data" / "cleaned"

DELAYS_FILE = RAW  / "calculated_delays_all.csv"
GTFS_FILE   = CLEANED / "vta_with_weather.parquet"
OUT_PARQUET = CLEANED / "vta_final.parquet"
OUT_CSV     = CLEANED / "vta_final.csv"

SECTION = "=" * 65


# ---------------------------------------------------------------------------
# Step 1 – Load delay data
# ---------------------------------------------------------------------------

def load_delays(path: Path) -> pd.DataFrame:
    d = pd.read_csv(path)
    print(f"  Delay rows : {len(d):,}  |  columns: {list(d.columns)}")

    # Normalise join keys
    d["trip_id"]       = d["trip_id"].astype(str)
    d["stop_sequence"] = d["stop_sequence"].astype(int)

    # Verify uniqueness of join key
    dupes = d.duplicated(subset=["trip_id", "stop_sequence"]).sum()
    if dupes:
        print(f"  WARNING: {dupes} duplicate (trip_id, stop_sequence) pairs — "
              "keeping first occurrence")
        d = d.drop_duplicates(subset=["trip_id", "stop_sequence"], keep="first")

    print(f"  Unique (trip_id, stop_sequence) pairs : {len(d):,}")
    print(f"  is_delayed=1 rows : {d['is_delayed'].eq(1).sum():,}  "
          f"({d['is_delayed'].eq(1).mean()*100:.1f}%)")
    print(f"  delay_minutes range : "
          f"{d['delay_minutes'].min():.2f} → {d['delay_minutes'].max():.2f} min")
    return d


# ---------------------------------------------------------------------------
# Step 2 – Load GTFS + weather
# ---------------------------------------------------------------------------

def load_gtfs(path: Path) -> pd.DataFrame:
    df = pd.read_parquet(path)
    df["trip_id"]       = df["trip_id"].astype(str)
    df["stop_sequence"] = df["stop_sequence"].astype(int)
    print(f"  GTFS shape  : {df.shape[0]:,} rows × {df.shape[1]} cols")
    print(f"  Unique trips: {df['trip_id'].nunique():,}")
    return df


# ---------------------------------------------------------------------------
# Step 3 – Merge
# ---------------------------------------------------------------------------

# Delay columns to carry into the final dataset
DELAY_COLS = [
    "trip_id", "stop_sequence",
    "delay_minutes", "is_delayed",
    "speed_mph", "occupancy_label",
    "vehicle_id", "current_status_name",
    "snapshot_ts",          # when the GPS observation was made
    "actual_delay_seconds", # raw seconds for reference
]


def merge_delays(gtfs: pd.DataFrame, delays: pd.DataFrame) -> pd.DataFrame:
    delay_slim = (
        delays[[c for c in DELAY_COLS if c in delays.columns]]
        .rename(columns={"snapshot_ts": "delay_snapshot_ts",
                         "vehicle_id":  "delay_vehicle_id"})
    )

    merged = gtfs.merge(
        delay_slim,
        on=["trip_id", "stop_sequence"],
        how="left",
        validate="many_to_one",
    )

    # For unmatched rows: is_delayed = 0 (not confirmed delayed)
    merged["is_delayed"] = (
        merged["is_delayed"].fillna(0).astype("Int8")
    )

    return merged


# ---------------------------------------------------------------------------
# Step 4 – Report
# ---------------------------------------------------------------------------

def print_report(df: pd.DataFrame) -> None:
    total        = len(df)
    has_data     = df["delay_minutes"].notna().sum()
    pct_coverage = has_data / total * 100
    delayed      = df["is_delayed"].eq(1).sum()
    pct_delayed  = delayed / has_data * 100 if has_data > 0 else 0.0

    dv = df["delay_minutes"].dropna()

    print(f"\n  Total rows                      : {total:>9,}")
    print(f"  Rows with delay observation     : {has_data:>9,}  ({pct_coverage:.2f}%)")
    print(f"  Rows without delay data (NaN)   : {total - has_data:>9,}")
    print(f"  is_delayed = 1  (> 5 min late)  : {delayed:>9,}  "
          f"({pct_delayed:.2f}% of matched rows)")
    print(f"\n  Average delay (matched)   : {dv.mean():>7.2f} min")
    print(f"  Median  delay (matched)   : {dv.median():>7.2f} min")
    print(f"  Max     delay (matched)   : {dv.max():>7.2f} min")
    print(f"  Min     delay (matched)   : {dv.min():>7.2f} min")

    print(f"\n  Trips with delay data     : "
          f"{df.loc[df['delay_minutes'].notna(), 'trip_id'].nunique():,} "
          f"/ {df['trip_id'].nunique():,} total")

    # Occupancy breakdown
    if "occupancy_label" in df.columns:
        occ = df["occupancy_label"].value_counts(dropna=False)
        print(f"\n  Occupancy distribution (matched rows):")
        for label, cnt in occ.items():
            print(f"    {str(label):<32} {cnt:>7,}")

    # Top 5 delayed routes (≥3 matched stops)
    print(f"\n  Top 5 most delayed routes (mean delay, ≥3 matched stops):")
    route_stats = (
        df.dropna(subset=["delay_minutes"])
        .groupby("route_short_name", observed=True)
        .agg(
            mean_delay  =("delay_minutes", "mean"),
            median_delay=("delay_minutes", "median"),
            n_stops     =("delay_minutes", "count"),
            pct_delayed =("is_delayed",    "mean"),
        )
        .query("n_stops >= 3")
        .sort_values("mean_delay", ascending=False)
        .head(5)
    )
    if route_stats.empty:
        print("    (No routes with ≥3 matched delay observations)")
    else:
        print(f"    {'Route':<14} {'Mean(min)':>10} {'Median':>8} "
              f"{'Stops':>7} {'%Late':>7}")
        print(f"    {'-'*50}")
        for route, row in route_stats.iterrows():
            print(f"    {str(route):<14} {row['mean_delay']:>+10.2f} "
                  f"{row['median_delay']:>+8.2f} "
                  f"{int(row['n_stops']):>7} "
                  f"{row['pct_delayed']*100:>6.1f}%")

    # Weather × delay
    if "is_rainy" in df.columns:
        print(f"\n  is_rainy distribution (matched rows):")
        print(df.dropna(subset=["delay_minutes"])["is_rainy"]
              .value_counts(dropna=False)
              .rename(index={0: "dry (0)", 1: "rainy (1)"})
              .to_string())


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> None:
    print(SECTION)
    print("06_merge_realtime.py — Merge Calculated Delays into Final Dataset")
    print(SECTION)

    # 1. Load delays
    print("\n[1] Loading calculated delays …")
    delays = load_delays(DELAYS_FILE)

    # 2. Load GTFS + weather
    print("\n[2] Loading GTFS + weather …")
    gtfs = load_gtfs(GTFS_FILE)

    # 3. Merge
    print("\n[3] Joining delays → GTFS on (trip_id, stop_sequence) …")
    final = merge_delays(gtfs, delays)
    print(f"  Result : {final.shape[0]:,} rows × {final.shape[1]} cols")
    new_cols = [c for c in final.columns if c not in gtfs.columns]
    print(f"  New cols added: {new_cols}")

    # 4. Report
    print(f"\n[4] Delay & coverage report")
    print_report(final)

    # 5. Final schema
    print(f"\n[5] Final schema ({final.shape[1]} columns):")
    schema = pd.DataFrame({
        "dtype":      final.dtypes.astype(str),
        "null_count": final.isnull().sum(),
        "null_%":     (final.isnull().sum() / len(final) * 100).round(2),
    })
    print(schema.to_string())

    # 6. Sample delayed rows
    sample = final[final["is_delayed"].eq(1)]
    if not sample.empty:
        print(f"\n[6] Sample delayed rows (is_delayed=1, top 5 by delay):")
        show = ["trip_id", "route_short_name", "stop_sequence",
                "arrival_sec", "delay_minutes", "is_delayed",
                "speed_mph", "occupancy_label", "current_status_name"]
        show = [c for c in show if c in final.columns]
        print(sample[show].sort_values("delay_minutes", ascending=False)
              .head(5).to_string(index=False))
    else:
        print("\n[6] No is_delayed=1 rows found.")

    # 7. Save
    print(f"\n[7] Saving outputs …")
    final.to_parquet(OUT_PARQUET, index=False)
    print(f"  Parquet → {OUT_PARQUET.name}  "
          f"({final.shape[0]:,} rows × {final.shape[1]} cols)")

    csv_df = final.copy()
    for col in csv_df.select_dtypes(include=["timedelta64[ns]"]).columns:
        csv_df[col] = csv_df[col].dt.total_seconds()
    csv_df.to_csv(OUT_CSV, index=False)
    print(f"  CSV    → {OUT_CSV.name}  "
          f"(timedelta cols serialised as total seconds)")

    print(f"\n{SECTION}")
    print("Done. Final dataset → data/cleaned/vta_final.*")
    print(SECTION)

if __name__ == "__main__":
    main()